### ISSUE TITLE
console.log() the result of interpreted JavaScript?

### ISSUE THREAD

**Issue by Unzor** [myuzio/JS-Interpreter#13]
How do I console.log() the result? Do I just do ```console.log(myInterpreter)?```

**Comment by myuzio** [comment]
@Unzor there are multiple ways of using this, including using it as an independent command-line tool, but I assume you mean to include this in a JS project that you already have? In that case something like this:

```js
import Interpreter from 'js-interpreter';
const code = `
  var x = 2;
  console.log('x is: ', x);
`;
const myInterpreter = new Interpreter(x);
myInterpreter.run();
```

You can take a look at the cli code for an example of how this library can be used: `src/cli.js`
